"""Safe command suggestions for mistyped local assistant commands."""

from __future__ import annotations

from difflib import get_close_matches


EXACT_COMMANDS = (
    "about",
    "about assistant",
    "action audit",
    "actions",
    "all tasks",
    "allowed actions",
    "backups",
    "briefing",
    "architecture",
    "bulk apply safety",
    "bulk apply review",
    "bulk rollback plan",
    "bulk write preflight",
    "bulk write checklist",
    "bulk restore checklist",
    "verify bulk write checklist",
    "verify bulk restore checklist",
    "bulk write command design",
    "bulk restore command design",
    "bulk replace apply plan",
    "bulk rename apply plan",
    "backup bulk replace",
    "backup bulk rename",
    "approve bulk replace",
    "approve bulk rename",
    "clear history",
    "clear memories",
    "command list",
    "command reference",
    "commands",
    "completed tasks",
    "daily briefing",
    "data report",
    "date",
    "delete task",
    "delete memory",
    "delete file",
    "deleted tasks",
    "deleted memories",
    "deleted files",
    "detected drives",
    "detected folders",
    "detected locations",
    "done tasks",
    "drafts",
    "draft email",
    "draft message",
    "draft network request",
    "due today",
    "due soon",
    "exit",
    "export data",
    "export safety reviews",
    "export signed reviews",
    "file tools",
    "file trash",
    "find",
    "find files",
    "forget history",
    "forget memories",
    "full help",
    "good morning",
    "health",
    "hello",
    "help",
    "help actions",
    "help briefing",
    "help data",
    "help history",
    "help memory",
    "help notes",
    "help search",
    "help status",
    "help tasks",
    "help voice",
    "history",
    "how do i launch",
    "local backup",
    "local data",
    "local files",
    "launch commands",
    "launch requests",
    "request file review",
    "request folder review",
    "request script review",
    "script review checklist",
    "verify script review checklist",
    "script allowlist preflight",
    "script execution readiness",
    "confirm script run simulation",
    "script allowlist entry simulation",
    "script allowlist design",
    "rename memory",
    "restore memory",
    "local models",
    "list models",
    "memories",
    "memory",
    "memory trash",
    "models",
    "next steps",
    "note",
    "notes",
    "open calculator",
    "open chrome",
    "open c drive",
    "open d drive",
    "open desktop",
    "open documents",
    "open downloads",
    "open file",
    "open notepad",
    "open paint",
    "open project folder",
    "open settings",
    "open this pc",
    "ollama models",
    "outbox",
    "overdue",
    "overdue tasks",
    "paths",
    "file paths",
    "data paths",
    "privacy report",
    "preview replace",
    "preview rename files",
    "quit",
    "roadmap",
    "project roadmap",
    "recent history",
    "remember",
    "restore task",
    "restore deleted task",
    "restore file",
    "reopen task",
    "permissions",
    "permissions dashboard",
    "privacy",
    "safety",
    "safety dashboard",
    "safety snapshot",
    "safety snapshot launch",
    "safety snapshot shell",
    "safety snapshot scripts",
    "safety snapshot scripts drift",
    "safety snapshot scripts drift signature",
    "safety snapshot scripts drift hash",
    "safety snapshot scripts drift path",
    "safety snapshot scripts drift threshold 2",
    "search",
    "search file names",
    "search files",
    "security",
    "start commands",
    "settings",
    "safe shell",
    "shell commands",
    "shell command guide",
    "shell command wizard",
    "shell allowlist guide",
    "shell review checklist",
    "verify shell checklist",
    "shell wizard",
    "show backups",
    "show history",
    "show memories",
    "show notes",
    "show drafts",
    "show settings",
    "show tasks",
    "status",
    "system status",
    "system architecture",
    "task",
    "task history",
    "task trash",
    "task stats",
    "task summary",
    "tasks",
    "tasks due today",
    "tasks due soon",
    "startup commands",
    "time",
    "today",
    "todo",
    "todo list",
    "todo stats",
    "upcoming",
    "upcoming tasks",
    "check voice",
    "speech confidence",
    "export voice audit",
    "voice action audit",
    "voice audit",
    "voice audit confidence low",
    "voice audit event action_preview",
    "voice audit retention keep 100",
    "prune voice audit keep 100",
    "voice confidence",
    "voice confidence status",
    "voice drill",
    "voice safety drill",
    "voice setup",
    "voice status",
    "wake mode",
    "wake status",
    "wake voice",
    "what can you do",
    "what can you open",
    "what next",
    "where is my data",
    "windows drives",
    "windows folders",
    "windows locations",
    "what is the date",
    "what time is it",
)

ARGUMENT_COMMANDS = {
    "find": "find <text>",
    "draft": "draft message to <recipient>: <text>",
    "email": "draft email to <recipient> subject <subject>: <text>",
    "message": "draft message to <recipient>: <text>",
    "note": "note <text>",
    "remember": "remember <fact>",
    "run": "run shell <allowed command name>",
    "add": "add shell command <name>: <executable> [args...]",
    "remove": "remove shell command <name>",
    "checklist": "shell review checklist <allowed command name>",
    "verify": "verify shell checklist <allowed command name>",
    "bulk": "bulk apply safety",
    "request": "request app <name>: <exe>",
    "search": "search <text>",
    "files": "file tools",
    "list": "list files in <folder>",
    "open": "open file in <folder> <relative path>",
    "read": "read file in <folder> <relative path>",
    "preview": "preview replace in <folder> find <text> with <text>",
    "trash": "file trash",
    "task": "task <task>",
    "todo": "todo <task>",
    "rename": "rename task <number> to <text>",
    "delete": "delete task <number>",
    "restore": "restore task <completed number>",
    "reopen": "reopen task <completed number>",
    "due": "due <number> YYYY-MM-DD",
    "clear": "clear due <number>",
}


def suggest_commands(text: str, *, limit: int = 3) -> list[str]:
    """Suggest likely built-in commands without executing anything."""
    normalized = " ".join(text.strip().lower().split())
    if not normalized:
        return []

    exact_matches = get_close_matches(
        normalized,
        EXACT_COMMANDS,
        n=limit,
        cutoff=0.78,
    )
    if exact_matches:
        return exact_matches

    first_word = normalized.split(maxsplit=1)[0]
    first_word_matches = get_close_matches(
        first_word,
        tuple(ARGUMENT_COMMANDS),
        n=1,
        cutoff=0.82,
    )
    if first_word_matches:
        return [ARGUMENT_COMMANDS[first_word_matches[0]]]

    return []


def unknown_command_text(text: str) -> str:
    """Return a safe unknown-command message with optional suggestions."""
    suggestions = suggest_commands(text)
    message = "I do not know how to do that yet."
    if suggestions:
        joined = ", ".join(suggestions)
        message += f" Did you mean: {joined}?"
    return f"{message} Type 'help' or 'command reference' for available commands."
