"""Offline command reference for the local assistant."""

from __future__ import annotations


def command_reference_text() -> str:
    """Return a categorized, deterministic list of supported commands."""
    return "\n".join(
        [
            "Command reference",
            "",
            "Basics:",
            "- hello, hi, hey",
            "- time, what time is it",
            "- date, today, what is the date",
            "- help",
            "- about, architecture, system architecture",
            "- safety, permissions, security, privacy",
            "- permissions dashboard, safety dashboard",
            "- safety snapshot, review snapshot",
            "- safety snapshot launch, safety snapshot shell, safety snapshot scripts",
            "- safety snapshot scripts drift",
            "- safety snapshot scripts drift signature|hash|path",
            "- safety snapshot scripts drift threshold <1-3>",
            "- roadmap, next steps, project roadmap",
            "- launch commands, start commands, startup commands",
            "- exit, quit, bye",
            "",
            "Status and local data:",
            "- status, health, system status",
            "- settings, show settings",
            "- paths, file paths, data paths",
            "- detected folders, windows folders, folder detection",
            "- detected drives, windows drives, drive detection",
            "- detected locations, windows locations",
            "- models, list models, ollama models",
            "- voice status, voice setup, check voice",
            "- voice confidence, voice confidence status, speech confidence",
            "- voice safety drill, voice drill, low confidence voice drill",
            "- voice audit, voice action audit, voice actions audit",
            "- voice audit confidence <level>, voice audit event <event>",
            "- export voice audit, export voice audit confidence <level>, export voice audit event <event>",
            "- voice audit retention keep <number>",
            "- prune voice audit keep <number>",
            "- wake status, wake voice, wake mode",
            "- data report, privacy report, local data",
            "- export data, backup data, local backup",
            "- export safety reviews, safety review export, export signed reviews",
            "- backups, list backups, show backups",
            "",
            "Memory:",
            "- remember <fact>",
            "- memories, memory, show memories",
            "- rename memory <number> to <new text>",
            "- delete memory <number>",
            "- memory trash, deleted memories",
            "- restore memory <trash number>, restore deleted memory <trash number>",
            "- forget memories, clear memories",
            "",
            "Notes:",
            "- note <text>",
            "- take note <text>",
            "- notes, show notes",
            "",
            "Outbox drafts:",
            "- outbox, drafts, show drafts",
            "- draft message to <recipient>: <text>",
            "- draft email to <recipient> subject <subject>: <text>",
            "- draft network request GET <url> [note]",
            "",
            "Tasks:",
            "- todo <task>",
            "- todo <task> due YYYY-MM-DD",
            "- tasks, todo list, show tasks",
            "- done <task number>, complete task <task number>",
            "- restore task <completed number>, reopen task <completed number>",
            "- delete task <number> (requires confirmation)",
            "- task trash, deleted tasks, restore deleted task <number>",
            "- due today, overdue, upcoming",
            "- due soon, task stats",
            "- rename task <number> to <text>",
            "- due <number> YYYY-MM-DD, clear due <number>",
            "- completed tasks, all tasks, task history",
            "",
            "Search:",
            "- search <text>",
            "- find <text>",
            "- file tools, local files, allowed files",
            "- list files in <folder>",
            "- search files in <folder> for <text>",
            "- find files in <folder> for <name text>",
            "- read file in <folder> <relative path>",
            "- open file in <folder> <relative path> (safe preview; does not launch)",
            "- launch file in <folder> <relative path> (requires confirmation and file-type allowlist)",
            "- file type trust <extension>",
            "- trust file type source <extension>: <source path>[; <source path>...]",
            "- trust file type signer <extension>: <signer token>[; <signer token>...]",
            "- trust file type thumbprint <extension>: <thumbprint>[; <thumbprint>...]",
            "- trust file type issuer <extension>: <issuer token>[; <issuer token>...]",
            "- trust file type validity <extension>: required|off",
            "- trust file type revocation <extension>: required|off|ocsp|crl|both",
            "- clear file type trust <extension>",
            "- preview replace in <folder> find <text> with <text> (dry run only)",
            "- preview rename files in <folder> replace <name text> with <name text> (dry run only)",
            "- bulk apply safety",
            "- bulk replace apply plan in <folder> find <text> with <text> (safety plan only)",
            "- bulk rename apply plan in <folder> replace <name text> with <name text> (safety plan only)",
            "- backup bulk replace in <folder> find <text> with <text> (copies planned files; does not apply)",
            "- backup bulk rename in <folder> replace <name text> with <name text> (copies planned files; does not apply)",
            "- approve bulk replace in <folder> find <text> with <text> files <numbers|all> (approval only)",
            "- approve bulk rename in <folder> replace <name text> with <name text> files <numbers|all> (approval only)",
            "- bulk apply review (audit-linked review only; does not apply)",
            "- bulk rollback plan (restore plan only; does not restore)",
            "- bulk write preflight (validates hashes and signs review metadata only; does not write or restore)",
            "- bulk write checklist (operator checklist only; does not write)",
            "- bulk restore checklist (operator checklist only; does not restore)",
            "- verify bulk write checklist (integrity check only; does not write)",
            "- verify bulk restore checklist (integrity check only; does not restore)",
            "- bulk write command design (design only; does not write)",
            "- bulk restore command design (design only; does not restore)",
            "- delete file in <folder> <relative path> (requires confirmation)",
            "- file trash, deleted files, restore file <trash number>",
            "",
            "Briefing and history:",
            "- briefing, daily briefing, good morning",
            "- history, show history, recent history",
            "- clear history, forget history",
            "",
            "Safe local actions:",
            "- actions, allowed actions, what can you open",
            "- launch requests, app requests, script requests",
            "- script allowlist design (design only; does not allowlist or run scripts)",
            "- file type allowlist, file launch allowlist",
            "- allow file type <extension>",
            "- disallow file type <extension>, remove file type <extension>",
            "- file type trust <extension>",
            "- trust file type source <extension>: <source path>[; <source path>...]",
            "- trust file type signer <extension>: <signer token>[; <signer token>...]",
            "- trust file type thumbprint <extension>: <thumbprint>[; <thumbprint>...]",
            "- trust file type issuer <extension>: <issuer token>[; <issuer token>...]",
            "- trust file type validity <extension>: required|off",
            "- trust file type revocation <extension>: required|off|ocsp|crl|both",
            "- clear file type trust <extension>",
            "- request app <name>: <exe>",
            "- request script review <name>: <path> (static inspection summary; does not run)",
            "- script review checklist <request number> (review-only; does not run)",
            "- verify script review checklist <request number> (integrity check only; does not run)",
            "- script allowlist preflight <request number> (review-only; does not run or allowlist)",
            "- script execution readiness <request number> (review-only bundle; does not run or allowlist)",
            "- confirm script run simulation <request number>: confirm script run (review-only; does not run or allowlist)",
            "- script allowlist entry simulation <request number>: <interpreter> [args...] (review-only; does not run or allowlist)",
            "- request file review <name>: <path>",
            "- request folder review <name>: <path>",
            "- launch file in <folder> <relative path>",
            "- shell commands, safe shell, allowed shell commands",
            "- safety snapshot (read-only launch and shell review summary)",
            "- safety snapshot launch (launch requests only)",
            "- safety snapshot shell (shell review records only)",
            "- safety snapshot scripts (script review requests only)",
            "- safety snapshot scripts drift (script requests with active drift warnings only)",
            "- safety snapshot scripts drift signature (drift triage for signature issues only)",
            "- safety snapshot scripts drift hash (drift triage for hash issues only)",
            "- safety snapshot scripts drift path (drift triage for path issues only)",
            "- safety snapshot scripts drift threshold <1-3> (only requests with that many or more active warning types)",
            "- shell command guide, shell allowlist guide",
            "- shell command wizard, shell wizard",
            "- add shell command <name>: <executable> [args...]",
            "- shell wizard add <name>: <executable> [args...]",
            "- shell review checklist <allowed command name> (review-only; does not run)",
            "- verify shell checklist <allowed command name> (integrity check only; does not run)",
            "- remove shell command <name>",
            "- run shell <allowed command name> (requires confirmation)",
            "- open calculator",
            "- open notepad",
            "- open paint",
            "- open chrome",
            "- open C drive, open D drive",
            "- open this pc",
            "- open settings",
            "- open documents",
            "- open downloads",
            "- open desktop",
            "- open project folder",
            "",
            "Safety notes:",
            "- App and folder actions require confirmation.",
            "- Windows folder/drive detection is read-only and does not update allowlists.",
            "- Unlisted apps, scripts, files, and folders do not open; requests are local review notes only.",
            "- Script allowlist design defines future static review, hash pinning, checklist, and confirmation gates without enabling script execution.",
            "- Script review checklist creates local review files and still does not run or allowlist scripts.",
            "- Script checklist verification validates local checklist signatures and no-run flags without running scripts.",
            "- Script allowlist preflight creates a signed review record without running or allowlisting scripts.",
            "- Script execution readiness creates a signed no-run readiness bundle with exact-hash, checklist, and preflight gate details.",
            "- Confirmed script run simulation validates readiness signatures and current hash matching, then records no-run audit metadata only.",
            "- Script allowlist-entry simulation validates interpreter policy, argument policy, and path pinning against readiness metadata, then records no-run audit metadata only.",
            "- File review requests add read-only file-type risk notes and show whether the file type is explicitly allowlisted for future launch workflows.",
            "- File types must be explicitly allowlisted before any future file launch workflow can proceed.",
            "- Launch file in <folder> <relative path> requires both explicit file-type allowlisting and confirmation before Windows open.",
            "- Optional trust signals can require launch path to be inside trusted source roots, signed by trusted signer tokens, and/or pinned to exact certificate thumbprints.",
            "- Optional trust signals can also require certificate issuer token match, currently-valid certificate dates, and revocation-status checks (online, OCSP, CRL, or both endpoint requirements).",
            "- Named safe shell commands require confirmation and run without shell=True.",
            "- Adding a shell command saves static review notes, static risk scoring, and signed review metadata but does not run it.",
            "- The shell command wizard guides allowlist edits and still does not run saved commands.",
            "- Shell review checklist creates local review files and still does not run saved commands.",
            "- Shell checklist verification validates local checklist signatures and still does not run saved commands.",
            "- Safety snapshot summarizes launch requests, shell review metadata, and filtered script review requests without opening, running, or approving anything.",
            "- Script drift snapshot quickly lists only script requests whose latest readiness/simulation records show signature/hash/path mismatch warnings.",
            "- Filtered script drift snapshots support targeted triage by signature, hash, or path warning type.",
            "- Script drift snapshot threshold filtering prioritizes requests with two or more active warning types.",
            "- Open file in <folder> shows an in-assistant text preview and does not launch files in Windows.",
            "- Bulk file previews do not write, rename, or delete files.",
            "- Bulk apply plans describe backup, approval, and audit requirements without applying changes.",
            "- Bulk backups copy planned files to local exports and do not modify originals.",
            "- Bulk approvals save local manifests and do not apply changes.",
            "- Bulk apply review creates a local review manifest and action audit entry without applying changes.",
            "- Bulk rollback plan creates a restore plan from the latest backup without restoring files.",
            "- Bulk write preflight validates backup, approval, review, rollback, and manifest hashes, then saves signed review metadata without writing files.",
            "- Bulk write/restore checklists create local operator review files without writing or restoring files.",
            "- Bulk checklist verification validates checklist signatures and source manifests without writing or restoring files.",
            "- Safety review export writes a local signed-review audit bundle for shell, bulk, and script reviews without running commands, running scripts, or applying files.",
            "- Bulk write/restore command designs define future confirmed commands without enabling writes.",
            "- File delete moves text files to assistant trash and requires confirmation.",
            "- Sending messages/emails and making network requests are not enabled; local drafts only.",
            "- Bulk file modification and raw arbitrary shell commands are not enabled.",
            "- Use permissions dashboard to review safety-limited feature status before enabling more power.",
            "- Unknown questions use the local Ollama model only when LLM mode is enabled.",
            "- Wake voice mode is optional and must be launched with --wake.",
            "- Voice confidence is read-only and never confirms or runs actions.",
            "- Low-confidence spoken actions require the extra phrase 'confirm action' before they run.",
            "- Voice safety drill simulates the low-confidence flow without using the microphone or opening anything.",
            "- Voice audit stores local text summaries of recognized voice commands; audio is never stored.",
            "- Voice audit filters and export are read-only/local-only and never include audio.",
            "- Voice audit retention preview is read-only; pruning requires confirmation and writes a local backup first.",
        ]
    )
