"""Offline roadmap summary for the local assistant."""

from __future__ import annotations


def roadmap_text(name: str = "Jarvis") -> str:
    """Return a local-first project roadmap."""
    return "\n".join(
        [
            f"{name} roadmap",
            "",
            "Working now:",
            "- Command-line assistant",
            "- Tkinter desktop GUI",
            "- Local Ollama responses with CPU-safe GPU offload settings",
            "- Voice input with local Vosk model",
            "- Voice output with Windows speech",
            "- Optional wake-word style voice loop for command mode",
            "- Confirmation-gated named safe shell command runner",
            "- Guided safe shell command allowlist editor with validation",
            "- Static review notes for newly added safe shell commands",
            "- Static risk scoring for shell command allowlist changes",
            "- Signed review metadata for safe shell command allowlist changes",
            "- Local operator checklist files for shell command reviews",
            "- Shell checklist verification without running commands",
            "- Confirmed allowlisted app and folder opening",
            "- Read-only Windows folder and drive detection",
            "- Local review requests for unlisted apps/scripts without running them",
            "- Read-only file-type review for unlisted file open requests",
            "- Explicit per-file-type allowlisting before any future file launch workflow",
            "- Confirmation-gated file launch workflow using allowlisted folders and explicit file-type allowlisting",
            "- Optional per-file-type trust signals for source roots and signer-token checks",
            "- Strict signer identity options with exact certificate thumbprint pinning per file type",
            "- Certificate issuer token checks and currently-valid certificate date checks for launch trust policies",
            "- Optional certificate revocation checks for launch trust policies with online, OCSP, CRL, or both endpoint requirements",
            "- Signed-file launch review explains which revocation mode blocked or allowed launch",
            "- Static inspection summaries for script review requests without running scripts",
            "- Explicit script allowlisting design with static review gates before any script execution",
            "- Review-only script operator checklist manifests without enabling script execution",
            "- Signed script review export records without enabling script execution",
            "- Safe file listing, preview, search, trash, and restore inside allowlisted folders",
            "- Preview-only dry-run plans for bulk text replacement and filename renames",
            "- Backup, per-file approval, and audit safety plans for bulk file changes",
            "- Local backup creation for planned bulk file changes without applying them",
            "- Local per-file approval manifests for planned bulk file changes",
            "- Audit-linked bulk apply review manifests without applying changes",
            "- Rollback plans from local bulk backups without restoring files",
            "- Bulk write preflight manifests without writing or restoring files",
            "- Manifest hashes for bulk backups, approvals, apply reviews, rollback plans, and write preflights",
            "- Signed review metadata for bulk write preflight records",
            "- Local operator checklist files for future bulk write and restore reviews",
            "- Bulk write and restore checklist verification without applying changes",
            "- GUI buttons for read-only bulk checklist verification summaries",
            "- Local signed review export for shell, bulk, and script safety audit records",
            "- Read-only safety snapshots for recent launch and shell review requests",
            "- Read-only safety snapshot filtering by review type",
            "- Read-only script review snapshot filtering before any script execution",
            "- Script checklist verification details in read-only script review snapshots",
            "- Review-only script allowlist preflight records before any script execution",
            "- Script safety snapshots include script preflight status and signature details",
            "- Signed script execution readiness bundles with exact-hash, checklist+preflight binding, typed confirmation phrase, and no-run audit dry-run metadata",
            "- Read-only confirmed script run simulation with readiness signature validation and no-run audit metadata",
            "- Read-only script allowlist-entry simulation with interpreter policy, argument policy, and path-pinning checks",
            "- Script safety snapshots include latest readiness, run-simulation, and allowlist-entry simulation gate states per request",
            "- Script safety snapshots include explicit drift warnings for signature/hash/path mismatch states",
            "- Script safety snapshot drift view lists only requests with active drift warnings for faster triage",
            "- Script drift snapshots include warning-type breakdown counts for signature/hash/path remediation triage",
            "- Script drift snapshots support warning-type filtering for signature, hash, or path targeted review",
            "- Script drift snapshots support a minimum warning-type-count threshold to prioritize severe drift first",
            "- GUI controls and menu shortcuts for filtered read-only safety snapshots",
            "- Confirmed bulk write and restore command designs with rollback checks",
            "- Read-only voice confidence reporting before accepting spoken action confirmations",
            "- Second spoken confirmation phrase for low-confidence action commands",
            "- Read-only voice safety drill for low-confidence confirmation without using the microphone",
            "- Local text-only voice action audit summaries without storing audio",
            "- GUI voice audit review controls",
            "- Read-only voice audit filters and local text-only export",
            "- GUI buttons for filtered voice audit review and local export",
            "- Confirmed voice audit retention cleanup with local backup",
            "- GUI buttons for voice audit retention preview and confirmed pruning",
            "- Local memory, notes, tasks, history, search, briefing, reports, and backups",
            "- Per-memory rename, confirmed trash, memory trash review, and restore",
            "- Settings, GUI settings panel, persona, aliases, help, status, paths, safety, architecture, and GUI startup summaries",
            "- GUI controls for memory trash/restore and task edit/delete review",
            "- GUI voice controls for status, voice launch help, wake-loop help, action review, and copying wake launch commands",
            "- Voice action preview and correction with richer spoken phrases before confirmations execute actions",
            "- Task editing, restore, and confirmed task deletion",
            "",
            "Recommended next upgrades:",
            "- None queued right now. Suggest a specific area for the next reasonable upgrade.",
            "",
            "Not planned until safety is designed:",
            "- Raw arbitrary shell command execution.",
            "- Permanent file deletion or applying bulk file modification plans.",
            "- Sending messages, emails, or network requests on your behalf.",
            "- Automatically running or allowlisting unlisted apps or scripts.",
        ]
    )
